<?php $this->partial("common/partials/page-header", array('title' => $t->_('Help'), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="fa fa-list"></i>
                    วิธีการใช้งาน
                </h3>
            </div>
            <div class="box-content">
                <div class="row">
                    <div class="col-sm-6">
                        <h4>ชั้นตอนการกรอกข้อมูล</h4>
                        <ul class="gallery">
                            <li>
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput">
                                        <a href="#">
                                        <?php echo $this->tag->image(array("img/howto.jpg", 'class' => "img-responsive")); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="extras">
                                    <div class="extras-inner">
                                        <?php echo $this->tag->linkTo(array('img/howto.jpg', '<i class="fa fa-search"></i> ', 'class' => 'colorbox-image', 'rel' => 'group-1')) ?>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        
                    </div>
                    <div class="col-sm-6">
                        <h4>&nbsp;</h4>
                        <ol>
                            <li>Lorem ipsum labore</li>
                            <li>Lorem ipsum labore</li>
                            <li>Lorem ipsum labore</li>
                            <li>Lorem ipsum labore</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>