<?php use Phoenix\Models\ItemsCategory; ?>
<?php use Phalcon\Tag; ?>

<?php $this->partial("common/partials/page-header", array('title' => $t->_("Search Items"), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>
<?php echo $this->getContent(); ?>

<?php if(isset($keyword)) :?>
<div class="row">
    <div class="col-sm-12" style="margin-top:20px;">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $mt->_("Search result(s) for", array("keyword" => $keyword)) ?>
        </div>
    </div>
</div>
<?php endif ?>


<div class="row">
    <div class="col-sm-12">
        <div class="pull-left">
            <?php echo $this->tag->linkTo(array("guest", '<i class="fa fa-reply"></i> ' . $mt->_("Back"), 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Back"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="box box-color box-bordered">
            <div class="box-title">
                <h3>
                    <i class="fa fa-table"></i><?php echo $t->_("Items"); ?>
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-hover table-nomargin table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $t->_("Item Name"); ?></th>
                            <th><?php echo $t->_("Author"); ?></th>
                            <th><?php echo $t->_("Publisher"); ?></th>
                            <th class="col-sm-1"><?php echo $t->_("Publish"); ?></th>
                            <th><?php echo $t->_("Category"); ?></th>
                            <th class="col-sm-1"><?php echo $t->_("Status"); ?></th>
                            <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($page->items as $item) { ?>
                            <?php $itemCategory = ItemsCategory::findFirstByCatId($item->cat_id); 
                                if($itemCategory)
                                    $itemCategoryName =  $itemCategory->name;
                                else
                                    $itemCategoryName = $defaultNullData;
                            ?>
                            <tr>
                                <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $item->name) : $item->name ?></td>
                                <td><?php echo $author = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $item->author) : $item->author ?></td>
                                <td><?php echo $publisher = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $item->publisher) : $item->publisher ?></td>
                                <td><?php echo $publish = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $item->publish) : $item->publish ?></td>
                                <td><?php echo $itemCategoryName ?></td>
                                <td class='hidden-350'><?php echo $activeStatus = ($item->status) ? '<span class="label label-satgreen">' . $t->_("Active") . '</span>' : '<span class="label label-lightred">' . $t->_("Inactive") . '</span>'; ?></td>
                                <td class='hidden-480'>
                                    <?php echo $this->tag->linkTo(array("guest/view/" . $item->item_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

                <div class="tables-info pull-left">
                    <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                </div>

                <div class="table-pagination pull-right">
                    <a href="<?php echo $baseUri ?>guest/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                    <a href="<?php echo $baseUri ?>guest/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                    <a href="<?php echo $baseUri ?>guest/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                    <a href="<?php echo $baseUri ?>guest/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
