<?php use Phoenix\Models\Province; ?>

<?php $this->partial("common/partials/page-header", array('title' => $t->_("Item Description"), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="pull-left">
            <?php echo $this->tag->linkTo(array("guest", '<i class="fa fa-reply"></i> ' . $mt->_("Back"), 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Back"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="fa fa-user"></i>
                    <?php echo $t->_("Item"); ?>
                </h3>
            </div>
            <div class="box-content">
                <dl>
                    <dt><?php echo $t->_("Name"); ?></dt>
                    <dd>
                        <?php echo $item->name ?>
                    </dd>
                    <dt><?php echo $t->_("Author"); ?></dt>
                    <dd>
                        <?php echo $item->author ?>
                    </dd>
                    <dt><?php echo $t->_("Publisher"); ?></dt>
                    <dd>
                        <?php echo $item->publisher; ?>
                    </dd>
                    <dt><?php echo $t->_("ISBN/ISSN"); ?></dt>
                    <dd>
                        <?php echo $item->identity ?>
                    </dd>
                    <dt><?php echo $t->_("Publish"); ?></dt>
                    <dd>
                        <?php echo $item->publish ?>
                    </dd>
                    <dt><?php echo $t->_("Type"); ?></dt>
                    <dd>
                        <?php echo $item->type ?>
                    </dd>
                    <dt><?php echo $t->_("Category"); ?></dt>
                    <dd>
                        <?php echo $item->category ?>
                    </dd>
                    <dt><?php echo $t->_("Sub Category"); ?></dt>
                    <dd>
                        <?php echo $item->subCategory ?>
                    </dd>
                    <dt><?php echo $t->_("Group"); ?></dt>
                    <dd>
                        <?php echo $item->group ?>
                    </dd>
                    <dt><?php echo $t->_("Registered"); ?></dt>
                    <dd>
                        <?php echo $item->registered ?>
                    </dd>
                    <dt><?php echo $t->_("Author Code"); ?></dt>
                    <dd>
                        <?php echo $item->author_code ?>
                    </dd>
                    <dt><?php echo $mt->_("Status"); ?></dt>
                    <dd>
                        <?php echo $activeStatus = ($item->status) ? '<span class="label label-satgreen">' . $mt->_("Active") . '</span>' : '<span class="label label-lightred">' . $mt->_("Inactive") . '</span>'; ?>
                    </dd>
                    <dt><?php echo $mt->_("Image"); ?></dt>
                    <dd>
                        <ul class="gallery">
                            <li>
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 180px;">
                                        <a href="#">
                                        <?php echo $this->tag->image(array($itemMeta['image'])); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="extras">
                                    <div class="extras-inner">
                                        <?php echo $this->tag->linkTo(array($itemMeta['image'], '<i class="fa fa-search"></i> ', 'class' => 'colorbox-image', 'rel' => 'group-1')) ?>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="fa fa-info"></i>
                    <?php echo $mt->_("Information"); ?>
                </h3>
            </div>
            <div class="box-content">
                <dl>
                    <dt><?php echo $t->_("Print"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['print']->year . ' ' . $itemMeta['print']->month . ' ' . $itemMeta['print']->count ?>
                    </dd>
                    <dt><?php echo $t->_("Language"); ?></dt>
                    <dd>
                        <?php echo $item->item_language; ?>
                    </dd>
                    <dt><?php echo $t->_("Volume"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['volume'] ?>
                    </dd>
                    <dt><?php echo $t->_("Page"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['page'] ?>
                    </dd>
                    <dt><?php echo $t->_("Cost"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['cost']; ?>
                    </dd>
                    <dt><?php echo $t->_("Town"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['town']; ?>
                    </dd>
                    <dt><?php echo $t->_("Sponsor"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['sponsor'] ?>
                    </dd>
                    <dt><?php echo $t->_("Vendor"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['vendor'] ?>
                    </dd>
                    <dt><?php echo $t->_("Abstract"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['abstract'] ?>
                    </dd>
                    <dt><?php echo $t->_("Tag"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['tag'] ?>
                    </dd>
                    <dt><?php echo $mt->_("Note"); ?></dt>
                    <dd>
                        <?php echo $itemMeta['note'] ?>
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>