<div id="modalClearDataConfirm" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $mt->_("Delete All Data Confirmation"); ?></h4>
            </div>
            <!-- /.modal-header -->
            <div class="modal-body">
                <p><code><?php echo $mt->_("Are you sure you want to delete all data from system?"); ?> </code></p>
                <p><?php echo $mt->_("After click \"Yes\" button, the data can not restore."); ?></p>
                <p id="deleteTitle"></p>
            </div>
            <!-- /.modal-body -->
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $mt->_("No"); ?></button>
                <?php echo $this->tag->linkTo(array('tools/index/cleardata', $mt->_("Yes"), 'class' => 'btn btn-primary', 'id' => 'deleteID')); ?>
            </div>
            <!-- /.modal-footer -->
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
