<?php use Phalcon\Tag; ?>

<div align="center">
    <h1>Edit ComBPersonType</h1>
</div>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>

<?php echo $this->getContent(); ?>

<div align="left" style="margin-top:20px;">
    <?php echo $this->tag->linkTo(array("settings/persontype", '<i class="fa fa-reply"></i> Back', 'class' => 'btn', 'rel' => 'tooltip', 'title' => 'Back')) ?>

    <?php echo $this->tag->linkTo(array("settings/persontype/new", '<i class="fa fa-plus"></i> ประเภทบุคคล', 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => 'เพิ่มข้อมูล')) ?>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3><i class="fa fa-th-list"></i> <?php echo $t->_("persontype")?></h3>
            </div>
            <div class="box-content nopadding">

                <?php echo $this->tag->form(array("settings/persontype/save", "method" => "post", "class" => "form-horizontal form-bordered")) ?>

                    <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2"><?php echo $t->_("persontype"); ?></label>
                        <div class="col-sm-10">
                            <?php echo $this->tag->textField(array("PersonTypeName", "size" => 30, 'class' => 'form-control')) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-2"><?php echo $t->_("active-status"); ?><small>More information here</small></label>
                        <div class="col-sm-10">
                            <div class="radio">
                                <label>
                                    <?php echo Phalcon\Tag::radioField(array("ActiveStatus", "value" => "1"))?> <?php echo $t->_("active"); ?>
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <?php echo Phalcon\Tag::radioField(array("ActiveStatus", "value" => "0"))?> <?php echo $t->_("inactive"); ?>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <?php echo Phalcon\Tag::hiddenField(array("PersonTypeID")); ?>
                        <?php echo Phalcon\Tag::hiddenField(array("UserID")); ?>
                        <?php echo Phalcon\Tag::hiddenField(array("Version")); ?>
                        <?php echo $this->tag->submitButton(array('Save changes', 'class' => 'btn btn-primary')) ?>
                        <?php echo $this->tag->linkTo(array("settings/persontype", 'Cancel', 'class' => 'btn')) ?>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>