<?php use Phalcon\Tag; ?>

<div align="center">
    <h1><?php echo $t->_("persontype")?> <?php echo $mt->_("setting")?></h1>
</div>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>

<?php echo $this->getContent(); ?>

<div align="left" style="margin-top:20px;">
    <?php echo $this->tag->linkTo(array(array('for' => 'settings-full', 'controller' => 'persontype', 'action' => 'new'), '<i class="fa fa-plus"></i> '. $t->_("persontype"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $mt->_("add data"))) ?>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="box box-color box-bordered">
            <div class="box-title">
                <h3>
                    <i class="fa fa-table"></i>
                    <?php echo $t->_("persontype"); ?>
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-hover table-nomargin table-bordered usertable">
                    <thead>
                        <tr class='thefilter'>
                            <th><?php echo $t->_("id"); ?></th>
                            <th><?php echo $t->_("persontype"); ?></th>
                            <th class='hidden-350'><?php echo $t->_("status"); ?></th>
                            <th class='hidden-480'><?php echo $t->_("options"); ?></th>
                        </tr>
                        <tr>
                            <th><?php echo $t->_("id"); ?></th>
                            <th><?php echo $t->_("persontype"); ?></th>
                            <th class='hidden-350'><?php echo $t->_("status"); ?></th>
                            <th class='hidden-480'><?php echo $t->_("options"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            if(isset($page->items)){
                                foreach($page->items as $ComBPersonType){ 
                        ?>
                            <tr>
                                <td><?php echo $ComBPersonType->PersonTypeID ?></td>
                                <td><?php echo $ComBPersonType->PersonTypeName ?></td>
                                <td class='hidden-350'><?php echo $activeStatus = ($ComBPersonType->ActiveStatus) ? '<span class="label label-satgreen">เปิดใช้</span>' : '<span class="label label-lightred">ไม่ใช้</span>'; ?></td>
                                <td class='hidden-480'>
                                    <?php echo $this->tag->linkTo(array("settings/persontype/edit/" . $ComBPersonType->PersonTypeID, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("edit"))); ?>
                                    <?php echo $this->tag->linkTo(array("settings/persontype/delete/" . $ComBPersonType->PersonTypeID, '<i class="fa fa-trash-o"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("delete"))); ?>
                                    <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("delete") ?>" data-original-title="<?php echo $mt->_("delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $ComBPersonType->PersonTypeID ?>', '<?php echo $ComBPersonType->PersonTypeName ?>')"><i class="fa fa-trash-o"></i></a>
                                </td>
                            </tr>
                        <?php }
                            } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="modalDeleteConfirm" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
            </div>
            <!-- /.modal-header -->
            <div class="modal-body">
                <p>Are you sure you want to delete? </p>
                <p id="deleteTitle"></p>
            </div>
            <!-- /.modal-body -->
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">No</button>
                <?php echo $this->tag->linkTo(array('#', 'Yes', 'class' => 'btn btn-primary', 'id' => 'deleteID')); ?>
            </div>
            <!-- /.modal-footer -->
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<script>
        function deleteConfirm(id, title){
            $('#deleteID').attr("href", '/phoenix/settings/persontype/delete/' + id)
            $('#deleteTitle').html(title)
        }
</script>
