<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("ComBPersonType/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("ComBPersonType/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>PersonTypeID</th>
            <th>PersonTypeName</th>
            <th>Version</th>
            <th>UserID</th>
            <th>ActiveStatus</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $ComBPersonType) { ?>
        <tr>
            <td><?php echo $ComBPersonType->PersonTypeID ?></td>
            <td><?php echo $ComBPersonType->PersonTypeName ?></td>
            <td><?php echo $ComBPersonType->Version ?></td>
            <td><?php echo $ComBPersonType->UserID ?></td>
            <td><?php echo $ComBPersonType->ActiveStatus ?></td>
            <td><?php echo $this->tag->linkTo(array("ComBPersonType/edit/" . $ComBPersonType->PersonTypeID, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("ComBPersonType/delete/" . $ComBPersonType->PersonTypeID, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("ComBPersonType/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("ComBPersonType/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("ComBPersonType/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("ComBPersonType/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
