<?php $this->partial("common/partials/page-header", array('title' => $t->_($title), 'size' => 'big')) ?>

<?php echo $this->getContent() ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("academy/new", '<i class="fa fa-plus"></i> ' . $t->_("Create Academy"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Create Academy"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3>
                    <i class="fa fa-bars"></i>
                    <?php echo $t->_("Office Area"); ?>
                </h3>
            </div>
            <div class="box-content">
                <?php echo $this->tag->form(array("", "method" => "post", "class" => "form-validate form-vertical form-column", 'id' => "frmFindArea")) ?>
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <?php echo $form->render("areas") ?>
                                <address id="areaDetail"></address>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group pull-right">
                                <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>" class="btn btn-primary btn-large" id="areaLocation"><i class="fa fa-search"></i></i> <?php echo $mt->_("Search!"); ?> </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel-group panel-widget" id="ac3">
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#academy" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-table"></i> <?php echo $t->_($title); ?> <?php echo $mt->_("Latest"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="academy" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-hover table-nomargin table-bordered">
                            <thead>
                                <tr>
                                    <th class='hidden-480 col-sm-1'><?php echo $t->_("Code"); ?></th>
                                    <th><?php echo $t->_("Name"); ?></th>
                                    <th><?php echo $mt->_("Area"); ?></th>
                                    <th><?php echo $t->_("Province"); ?></th>
                                    <th><?php echo $t->_("Telephone"); ?></th>
                                    <th><?php echo $t->_("Last Update"); ?></th>
                                    <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($page->items as $academy) { 

                                $last_updated = $this->datetime->date(strtotime($academy->last_updated));

                                unset($areaName);
                                $areaName = $academy->area->name;
                                $areaNameSearch = strpos($areaName, "เขต");

                                if ($areaNameSearch == true) {
                                    $areaNumber = str_replace("สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาเขต", "", $areaName);
                                }else{
                                    $areaNumber = str_replace("องค์กรปกครองส่วนท้องถิ่น ", "", $areaName);
                                }
                                
                                $province = $academy->province->province_name;
                            ?>
                                <tr>
                                    <td><?php echo $academy->code ?></td>
                                    <td><?php echo $t->_("School") ?><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academy->name) : $academy->name ?></td>
                                    <td class='hidden-350'>
                                        <?php echo '<span class="label label-default">' . $areaNumber . '</span>'; ?>
                                    </td>
                                     <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academy->province->province_name) : $academy->province->province_name ?></td>
                                     <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academy->telephone) : $academy->telephone ?></td>
                                    <td><?php echo $last_updated ?></td>
                                    <td class='hidden-480'>
                                        <?php echo $this->tag->linkTo(array("academy/view/" . $academy->academy_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                        <?php if(isset($auth) && $auth['role'] == 'A') : ?>
                                            <?php echo $this->tag->linkTo(array("academy/edit/" . $academy->academy_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                            <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $academy->academy_id ?>', '<?php echo $academy->name ?>')"><i class="fa fa-trash-o"></i></a>
                                        <?php endif ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                        <div class="tables-info pull-left">
                            <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                        </div>

                        <div class="table-pagination pull-right">
                            <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                            <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                            <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                            <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#academy.panel-collapse collapse in -->
            </div>
            <!-- /.panel panel-default -->
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#basic" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-search"></i> <?php echo $mt->_("Basic Search"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="basic" class="panel-collapse collapse">
                    <div class="panel-body">
                        <?php echo $this->tag->form(array("academy/basicsearch", "method" => "post", "autocomplete" => "off", "class" => "form-vertical form-column form-bordered search-form")) ?>
                            <div class="input-group ">
                                <?php echo $this->tag->textField(array("keyword", 'class' => 'form-control', 'placeholder' => $mt->_("Search here..."))) ?>
                                <div class="input-group-btn">
                                    <?php echo $this->tag->submitButton(array($mt->_("Search!"), 'class' => 'btn btn-primary btn-large input-group-addon')) ?>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#basic.panel-collapse collapse -->
            </div>
        </div>
        <!-- /.panel-group -->
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        var getAcademiesUrl = "/academy/grabAcademies";
        var getAreasUrl = "/academy/grabArea";
        var getAcademyUrl = "/academy/grabAcademy";

        $("#areas").change(function() {
            var value = $(this).val();

            $("#area_id").val(value);
            $("#areaDetail").html('').hide();

            $.ajax({
                type: "POST",
                url: getAreasUrl,
                data: {"id": value},
                success: function(response){

                    area = $.parseJSON(response);
                    $("#areaDetail").html(
                        "<strong>" + area.name + "</strong>"
                        + "<br>" + area.address
                        + "<br>" + area.subdistrict_prefix + area.subdistrict_name
                        + " " + area.district_prefix + area.district.district_name
                        + " จังหวัด" + area.province.province_name
                        + " " + area.zipcode
                        + "<br><abbr title='Phone'>โทร:</abbr> " + area.telephone
                        + "<br><abbr title='Fax'>แฟกซ์:</abbr> " + area.fax
                    ).show('slow').fadeIn('slow');

                    $("#areaLocation").attr("href", '/academy/area/' + value);
                }
            });
        });

        $('#areas').val('<?php echo $area_id ?>').change();
    });

</script>

<?php $this->partial("academy/partials/modalDeleteConfirm", array('title' => 'Delete Academy', 'size' => 'big')) ?>


