<?php use Phoenix\Models\Academy; ?>
<?php use Phalcon\Tag; ?>

<?php $this->partial("common/partials/page-header", array('title' => $t->_("Search Academy"), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>
<?php echo $this->getContent(); ?>

<?php if(isset($keyword)) :?>
<div class="row">
    <div class="col-sm-12" style="margin-top:20px;">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $mt->_("Search result(s) for", array("keyword" => $keyword)) ?>
        </div>
    </div>
</div>
<?php endif ?>


<div class="row">
    <div class="col-sm-12">
        <div class="pull-left">
            <?php echo $this->tag->linkTo(array("academy", '<i class="fa fa-reply"></i> ' . $mt->_("Back"), 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Back"))) ?>
        </div>

        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("academy/new", '<i class="fa fa-plus"></i> ' . $t->_("Create Academy"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Create Academy"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="box box-color box-bordered">
            <div class="box-title">
                <h3>
                    <i class="fa fa-table"></i><?php echo $t->_("Academy"); ?>
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-hover table-nomargin table-bordered">
                    <thead>
                        <tr>
                            <th class='hidden-480 col-sm-1'><?php echo $t->_("Code"); ?></th>
                            <th><?php echo $t->_("Name"); ?></th>
                            <th><?php echo $mt->_("Area"); ?></th>
                            <th><?php echo $t->_("Province"); ?></th>
                            <th><?php echo $t->_("Telephone"); ?></th>
                            <th><?php echo $t->_("Last Update"); ?></th>
                            <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($page->items as $academy) { 

                        $last_updated = $this->datetime->date(strtotime($academy->last_updated));

                        unset($areaName);
                        $areaName = $academy->area->name;
                        $areaNumber = str_replace("สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาเขต", "", $areaName);
                        $province = $academy->province->province_name;
                    ?>
                        <tr>
                            <td><?php echo $academy->code ?></td>
                            <td><?php echo $t->_("School") ?><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academy->name) : $academy->name ?></td>
                            <td class='hidden-350'>
                                <?php echo '<span class="label label-default">' . $areaNumber . '</span>'; ?>
                            </td>
                             <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academy->province->province_name) : $academy->province->province_name ?></td>
                             <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academy->telephone) : $academy->telephone ?></td>
                            <td><?php echo $last_updated ?></td>
                            <td class='hidden-480'>
                                <?php echo $this->tag->linkTo(array("academy/view/" . $academy->academy_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                <?php if(isset($auth) && $auth['role'] == 'A') : ?>
                                    <?php echo $this->tag->linkTo(array("academy/edit/" . $academy->academy_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                    <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $academy->academy_id ?>', '<?php echo $academy->name ?>')"><i class="fa fa-trash-o"></i></a>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <div class="tables-info pull-left">
                    <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                </div>

                <div class="table-pagination pull-right">
                    <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                    <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                    <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                    <a href="<?php echo $baseUri ?>academy/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->partial("academy/partials/modalDeleteConfirm", array('title' => 'Delete Items', 'size' => 'big')) ?>
