<?php use Phalcon\Tag; ?>

<?php $this->partial("../../../views/common/partials/page-header", array('title' => $t->_("Search AcademicYear"), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>
<?php echo $this->getContent(); ?>

<?php if(isset($keyword)) :?>
<div class="row">
    <div class="col-sm-12" style="margin-top:20px;">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $mt->_("Search result(s) for", array("keyword" => $keyword)) ?>
        </div>
    </div>
</div>
<?php endif ?>


<div class="row">
    <div class="col-sm-12">
        <div class="pull-left">
            <?php echo $this->tag->linkTo(array("settings/academicyears", '<i class="fa fa-reply"></i> ' . $mt->_("Back"), 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Back"))) ?>
        </div>

        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("settings/academicyears/new", '<i class="fa fa-plus"></i> ' . $t->_("Create AcademicYear"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Create AcademicYear"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="box box-color box-bordered">
            <div class="box-title">
                <h3>
                    <i class="fa fa-table"></i><?php echo $t->_("AcademicYear"); ?>
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-hover table-nomargin table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $t->_("Id"); ?></th>
                            <th><?php echo $t->_("AcademicYear Name"); ?></th>
                            <th><?php echo $t->_("AcademicYear Term"); ?></th>
                            <th><?php echo $t->_("AcademicYear Start"); ?></th>
                            <th><?php echo $t->_("AcademicYear End"); ?></th>
                            <th class='hidden-480 col-sm-1'><?php echo $mt->_("Options"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($page->items as $academicyear) { ?>
                        <tr>
                            <td><?php echo $id = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->academicyear_id) : $academicyear->academicyear_id ?></td>
                            <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->name) : $academicyear->name ?></td>
                            <td><?php echo $term = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->term) : $academicyear->term ?></td>
                            <td><?php echo $start = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->start) : $academicyear->start ?></td>
                            <td><?php echo $end = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->end) : $academicyear->end ?></td>
                            <td class='hidden-480'>
                                <?php echo $this->tag->linkTo(array("settings/academicyears/edit/" . $academicyear->academicyear_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $academicyear->academicyear_id ?>', '<?php echo $academicyear->name ?>')"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <div class="tables-info pull-left">
                    <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                </div>

                <div class="table-pagination pull-right">
                    <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                    <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                    <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                    <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->partial("items_type/partials/modalDeleteConfirm", array('title' => $t->_("Delete AcademicYear"), 'size' => 'big')) ?>
