<div class="row">
    <div class="col-sm-12">
        <div class="box box-color box-bordered disappear" id="profile">
            <div class="box-title">
                <h3>
                    <i class="fa fa-bars"></i>
                    Member Profile
                </h3>
                <div class="actions">
                    <a href="#" class="btn btn-mini content-refresh">
                        <i class="fa fa-eye"></i>
                    </a>
                    <a href="#" class="btn btn-mini content-remove">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a href="#" class="btn btn-mini content-slideUp">
                        <i class="fa fa-angle-down"></i>
                    </a>
                </div>
            </div>
            <div class="box-content">
                <div class="row">
                    <div class="col-sm-7">
                        <ul class="stats">
                            <li class="lightgrey">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="">
                                            <span id="image"></span>
                                            <span class="name" style="text-align: center;display: block; color:white;">หมู่โลหิต <strong id="bloodgroup" style="font-size:20px;">B</strong></span> 
                                        </div>
                                    </div>
                                    <div class="col-sm-9">
                                        <div class="details" style="line-height: 35px;margin-top: 20px;">
                                            <span class="name">ชื่อ <strong id="name" style="font-size:30px;"></strong></span>
                                            <span class="name">Name <strong style="font-size:24px;" id="name_en"></strong></span>
                                            <span class="name">เลขประจำตัวประชาขน <strong class="name" id="citizen_id" style="font-size:22px;"></strong></span>
                                            <span style="float:left;">เลขที่สมาชิก <strong class="name" id="code" style="font-size:20px;"></strong></span>
                                            <span style="float:left;margin-left: 20px;">ประเภทสมาชิก <strong class="name" id="type" style="font-size:22px;"></strong></span> <br>
                                        </div>
                                    </div>
                                </div>
                                
                            </li>
                        </ul>

                    </div>
                    <div class="col-sm-5">
                        <ul class="stats">
                            <li class="blue">
                                <i class="fa fa-map-marker"></i>
                                <div class="details">
                                    <span>จังหวัด</span>
                                    <span id="academy_province" class="big"></span>
                                    <span id="geo" class="big"></span>
                                </div>
                            </li>
                            <li class="green">
                                <i class="fa fa-bank"></i>
                                <div class="details">
                                    <span>โรงเรียน</span>
                                    <span id="academy" class="big"></span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>