<?php $this->partial("../../../views/common/partials/page-header", array('title' => $t->_("Template"), 'size' => 'big')) ?>

<?php echo $this->getContent() ?>
<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>




<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="fa fa-edit"></i><?php echo $t->_("Download Data Template") ?></h3>
            </div>
            <div class="box-content">
                <p>
                    <a href="/tools/template/1.0/SuperLibraryTemplate.zip" target="_blank" class="btn-block btn btn-large"><strong><?php echo $t->_("Download") ?></strong></a>
                </p>
            </div>
        </div>
    </div>
</div>