<?php use Phoenix\Models\Academy; ?>
<?php $this->partial("common/partials/page-header", array('title' => $t->_('Events'), 'size' => 'big')) ?>

<?php echo $this->getContent() ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("events/new", '<i class="fa fa-plus"></i> ' . $t->_("Create Event"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Create Event"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel-group panel-widget" id="ac3">
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#events" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-table"></i> <?php echo $t->_($title); ?> <?php echo $mt->_("Latest"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="events" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-hover table-nomargin table-bordered">
                            <thead>
                                <tr>
                                    <th class='hidden-480 col-sm-1'><?php echo $t->_("Code"); ?></th>
                                    <th><?php echo $t->_("Name"); ?></th>
                                    <th><?php echo $t->_("Detail"); ?></th>
                                    <th><?php echo $t->_("Venues"); ?></th>
                                    <th><?php echo $t->_("Event Start"); ?></th>
                                    <th><?php echo $t->_("Event End"); ?></th>
                                    <th><?php echo $t->_("Organizer"); ?></th>
                                    <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($page->items as $event) { 

                                $start = $this->datetime->date(strtotime($event->start));
                                $end = $this->datetime->date(strtotime($event->end));
                            ?>
                                <tr>
                                    <td><?php echo $event->event_id ?></td>
                                    <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $event->name) : $event->name ?></td>
                                    <td><?php echo $event->detail ?></td>
                                    <td><?php echo $event->venues ?></td>
                                    <td><?php echo $start ?></td>
                                    <td><?php echo $end ?></td>
                                    <td><?php echo $event->organizer ?></td>
                                    <td class='hidden-480'>
                                        <?php #echo $this->tag->linkTo(array("events/view/" . $event->event_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                        <?php echo $this->tag->linkTo(array("events/edit/" . $event->event_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                        <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $event->event_id ?>', '<?php echo $event->name ?>')"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                        <div class="tables-info pull-left">
                            <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                        </div>

                        <div class="table-pagination pull-right">
                            <a href="<?php echo $baseUri ?>events/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                            <a href="<?php echo $baseUri ?>events/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                            <a href="<?php echo $baseUri ?>events/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                            <a href="<?php echo $baseUri ?>events/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#events.panel-collapse collapse in -->
            </div>
            <!-- /.panel panel-default -->
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#basic" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-search"></i> <?php echo $mt->_("Basic Search"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="basic" class="panel-collapse collapse">
                    <div class="panel-body">
                        <?php echo $this->tag->form(array("events/basicsearch", "method" => "post", "autocomplete" => "off", "class" => "form-vertical form-column form-bordered search-form")) ?>
                            <div class="input-group ">
                                <?php echo $this->tag->textField(array("keyword", 'class' => 'form-control', 'placeholder' => $mt->_("Search here..."))) ?>
                                <div class="input-group-btn">
                                    <?php echo $this->tag->submitButton(array($mt->_("Search!"), 'class' => 'btn btn-primary btn-large input-group-addon')) ?>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#basic.panel-collapse collapse -->
            </div>
            <!-- /.panel panel-default -->
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#advance" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-search"></i> <?php echo $mt->_("Advanced Search"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="advance" class="panel-collapse collapse">
                    <div class="panel-body">
                        <?php echo $this->tag->form(array("events/search", "method" => "post", "autocomplete" => "off", "class" => "form-horizontal form-bordered")) ?>
                            <?php $this->partial("events/partials/formEvents") ?>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#advance.panel-collapse collapse in -->
            </div>
            <!-- /.panel panel-default -->
        </div>
        <!-- /.panel-group -->
    </div>
</div>

<?php $this->partial("events/partials/modalDeleteConfirm", array('title' => 'Delete Event', 'size' => 'big')) ?>


