<div class="tab-content">
    <div class="tab-pane active" id="tab-account">
        <div class="row">
            <div class="col-sm-12">
                <!--First Tab-->
                <div class="row">
                    <div class="col-sm-6 col-left">
                        <div class="form-group">
                            <label for="name" class="control-label">
                                <?php echo $t->_("Name"); ?>
                            </label>
                            <?php echo $form->render("name") ?>
                        </div>
                        <div class="form-group">
                            <label for="address" class="control-label">
                                <?php echo $mt->_("Address"); ?>
                           </label>
                            <?php echo $form->render("address") ?>
                        </div>
                        <div class="form-group">
                            <label for="province" class="control-label">
                                <?php echo $mt->_("Province"); ?>
                            </label>
                            <?php echo $form->render("province") ?>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4">
                                    <label for="zipcode" class="control-label">
                                        <?php echo $mt->_("Zipcode"); ?>
                                   </label>
                                    <?php echo $form->render("zipcode") ?>
                                </div>
                                <div class="col-sm-8">
                                    <label for="email" class="control-label">
                                        <?php echo $mt->_("Email"); ?>
                                   </label>
                                    <?php echo $form->render("email") ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="division_id" class="control-label">
                                <?php echo $t->_("Division"); ?>
                           </label>
                            <?php echo $form->render("division_id") ?>
                        </div>
                    </div>

                    <div class="col-sm-6 col-right">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-5">
                                    <label for="code" class="control-label"><?php echo $t->_("Code"); ?></label>
                                    <?php echo $form->render("code") ?>
                                </div>
                                <div class="col-sm-3">
                                    <label for="smis_code" class="control-label"><?php echo $t->_("SMIS Code"); ?></label>
                                    <?php echo $form->render("smis_code") ?>
                                </div>
                                <div class="col-sm-4">
                                    <label for="ministry_code" class="control-label"><?php echo $t->_("Ministry Code"); ?></label>
                                    <?php echo $form->render("ministry_code") ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address2" class="control-label">
                                <?php echo $mt->_("Address"); ?>
                                <small> (<?php echo $mt->_("Additional"); ?>) </small>
                           </label>
                            <?php echo $form->render("address2") ?>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label for="district" class="control-label">
                                        <?php echo $mt->_("District"); ?>
                                    </label>
                                    <?php echo $form->render("district") ?>
                                </div>
                                <div class="col-sm-6">
                                    <label for="subdistrict" class="control-label">
                                        <?php echo $mt->_("Sub District"); ?>
                                    </label>
                                    <?php echo $form->render("subdistrict") ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label for="telephone" class="control-label">
                                        <?php echo $mt->_("Telephone"); ?>
                                        <small><?php echo $mt->_("Format Telephone"); ?></small>
                                    </label>
                                    <?php echo $form->render("telephone") ?>
                                </div>

                                <div class="col-sm-6">
                                    <label for="fax" class="control-label">
                                        <?php echo $mt->_("Fax"); ?>
                                        <small><?php echo $mt->_("Format Fax"); ?></small>
                                   </label>
                                    <?php echo $form->render("fax") ?>
                                </div>
                            </div>
                        </div>

                        
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-3">
                                    <label for="meta[student-middle]" class="control-label">
                                        <?php echo $t->_("Middle School"); ?>
                                    </label>
                                    <?php echo $form->render("meta[student-middle]") ?>
                                </div>
                                <div class="col-sm-3">
                                    <label for="meta[student-high]" class="control-label">
                                        <?php echo $t->_("High School"); ?>
                                    </label>
                                    <?php echo $form->render("meta[student-high]") ?>
                                </div>
                                <div class="col-sm-2">
                                    <label for="meta[student-ep]" class="control-label">
                                        <?php echo $t->_("EP"); ?>
                                    </label>
                                    <?php echo $form->render("meta[student-ep]") ?>
                                </div>
                                <div class="col-sm-2">
                                    <label for="meta[student-mep]" class="control-label">
                                        <?php echo $t->_("MEP"); ?>
                                    </label>
                                    <?php echo $form->render("meta[student-mep]") ?>
                                </div>
                                <div class="col-sm-2">
                                    <label for="meta[student-gifted]" class="control-label">
                                        <?php echo $t->_("Gifted"); ?>
                                    </label>
                                    <?php echo $form->render("meta[student-gifted]") ?>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-actions pull-right">
                            <?php echo $this->tag->hiddenField("area_id") ?>
                            <?php echo $this->tag->submitButton(array($mt->_('Save Changes'), 'class' => 'btn btn-primary')) ?>
                            <?php echo $this->tag->linkTo(array("academy", $mt->_('Cancel'), 'class' => 'btn')) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--tab-account-->

    <div class="tab-pane" id="tab-info">
        <div class="row">
            <div class="col-sm-12">
                <!--Second Tab-->
                <div class="row">
                    <div class="col-sm-6 col-left">
                        <div class="form-group">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 250px; height: 151px;">
                               
                                <?php echo $this->tag->image($academyMeta['image']); ?>

                                </div>
                                <div>
                                    <span class="btn btn-default btn-file">
                                        <span class="fileinput-new"><?php echo $mt->_("Select image"); ?></span>
                                    <span class="fileinput-exists"><?php echo $mt->_("Change"); ?></span>
                                    <?php echo $this->tag->fileField(array("image", 'id' => 'image')) ?>
                                    </span>
                                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput"><?php echo $mt->_("Remove"); ?></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-right">
                        <div class="form-group">
                            <label for="note" class="control-label"><?php echo $t->_("Note"); ?></label>
                            <?php echo $form->render("meta[note]") ?>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label for="website" class="control-label"><?php echo $t->_("Website"); ?>
                                        <small><?php echo $t->_("with http://"); ?></small>
                                    </label>
                                    <?php echo $form->render("meta[website]") ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-actions pull-right">
                            <?php echo $this->tag->submitButton(array($mt->_('Save Changes'), 'class' => 'btn btn-primary')) ?>
                            <?php echo $this->tag->linkTo(array("academy", $mt->_('Cancel'), 'class' => 'btn')) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--tab-info-->
</div>