<?php echo $this->tag->form(array("items_copy/save", "method" => "post", "class" => "form-vertical form-column form-bordered", 'enctype' => 'multipart/form-data', 'id' => 'itemCopyEdit')) ?>
    <div id="modalCopyEdit" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel"><?php echo $t->_("Edit Items"); ?> :  <strong><span id="editTitle"></span></strong> (copy #<span id="copyNumber"></span>)</h4>
                </div>
                <!-- /.modal-header -->
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12 nopadding col-left">
                            <div class="form-group">
                                <label for="textfield" class="control-label"><?php echo $mt->_("Status"); ?></label>
                                <?php echo $formCopy->render("copy-status") ?>
                            </div>
                            <div class="form-group">
                                <label for="registered" class="control-label"><?php echo $t->_("Registered"); ?>
                                    <small><?php echo $mt->_("Format Date"); ?></small>
                                </label>
                                <?php echo $formCopy->render("copy-registered") ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-body -->
                <div class="modal-footer">
                    <?php echo $this->tag->hiddenField("item_id") ?>
                    <?php echo $this->tag->hiddenField("copy_id") ?>
                    <button type="submit" class="btn btn-primary"><?php echo $mt->_("Save Changes"); ?></button>
                    <button type="button" class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $mt->_("Cancel"); ?></button>
                </div>
                <!-- /.modal-footer -->
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</form>

<script>
        function deleteConfirm(id, copy, title, status, registered){
            $('#editID').attr("href", '<?php echo $baseUri ?>items_copy/save/' + id);
            $('#editTitle').html(title);
            $('#copyNumber').html(copy);
            $('#copy_id').val(id);
            $('#copy-status').val(status);
            $('#copy-registered').val(registered);
        }

        //ajax get item copy data
        //jquery set default

</script>