<?php use Phoenix\Models\Academy; ?>
<?php use Phoenix\Models\MembersMeta; ?>
<?php $this->partial("common/partials/page-header", array('title' => $mt->_('Completed Data') . ' จังหวัด' . $provinceName . ' (' . $memberTotal . 'คน)', 'size' => 'big')) ?>

<?php echo $this->getContent() ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3>
                    <i class="fa fa-bars"></i>
                    <?php echo $t->_("Completed Data Notification to Admin"); ?>
                </h3>
            </div>
            <div class="box-content">
                <?php echo $this->tag->form(array("members/complete", "method" => "post", "class" => "form-validate form-vertical form-column", 'id' => "frmFindArea")) ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <p>กดปุ่มด้านล่างเพื่อยืนยันว่า ท่านได้กรอกข้อมูลสมาชิก ส.บ.ม.ท. จังหวัด <?php echo $provinceName ?> ครบถ้วนแล้ว</p>
                                <?php echo $this->tag->submitButton(array($mt->_('Completed Data') . ' (จังหวัด ' . $provinceName . ' ' . $memberTotal . 'คน)', 'class' => 'btn btn-primary'))?>
                                <p></p>
                                <p><code>หมายเหตุ : สามารถตรวจสอบข้อมูลทั้งหมด ได้จากรายชื่อด้านล่าง</code></p>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="panel-group panel-widget" id="ac3">
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#members" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-table"></i> <?php echo $t->_($title); ?> <?php echo ' จังหวัด' . $provinceName . ' (' . $memberTotal . 'คน)'; ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="members" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-hover table-nomargin table-bordered bigrow">
                            <thead>
                                <tr>
                                    <th><?php echo $t->_("Image"); ?></th>
                                    <th class='hidden-480 col-sm-1'><?php echo $t->_("Code"); ?></th>
                                    <th><?php echo $t->_("Name"); ?></th>
                                    <th><?php echo $t->_("Member Type"); ?></th>
                                    <th><?php echo $mt->_("School"); ?></th>
                                    <th><?php echo $t->_("Location"); ?></th>
                                    <th><?php echo $mt->_("Status"); ?></th>
                                    <th><?php echo $t->_("Registered"); ?></th>
                                    <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($page->items as $member) { 

                                $elementPeopleType = $this->elements->getMembersType();
                                $memberType = $elementPeopleType[$member->type];


                                $elementPrefix =$this->elements->getPrefixNameData();
                                $memberTitle = $elementPrefix[$member->title];

                                $registered = $this->datetime->date(strtotime($member->registered));

                                $academyName = $defaultNullData;
                                $areaName = $defaultNullData;
                                if(!empty($member->membersAcademy->academy_id)){
                                        $academy = Academy::findFirstByAcademy_id($member->membersAcademy->academy_id);
                                    if($academy){
                                        $academyName = $academy->name;
                                        $areaName = $academy->area->name;
                                    }
                                }

                                $areaNameSearch = strpos($areaName, "เขต");
                                if ($areaNameSearch == true) {
                                    $areaNumber = str_replace("สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาเขต", "", $areaName);
                                }else{
                                    $areaNumber = str_replace("องค์กรปกครองส่วนท้องถิ่น ", "", $areaName);
                                }

                                // $province = $member->province->province_name;
                                $province = $academy->province->province_name;

                                $memberCode = (empty($member->code)) ? $defaultNullData : $member->code;

                                $memberMeta = MembersMeta::findFirst("member_id = " . $member->member_id . "and meta_key = 'image'");

                                // var_dump($memberMeta);
                                // $memberMeta['image'] = $defaultMemberImage;

                                if(!empty($memberMeta->meta_value))
                                    $memberMetaImage = $uploadLocation . $memberMeta->meta_value;
                                else
                                    $memberMetaImage = $defaultMemberImage;
                                
                                // foreach ($membersMeta as $memberMeta) {
                                //     echo $memberMeta->meta_value;
                                    // if($memberMeta->meta_key == 'image')
                                    //     $memberMeta[$memberMeta->meta_key] =  $uploadLocation . $memberMeta->meta_value;
                                    // else
                                    //     $memberMeta[$memberMeta->meta_key] = $memberMeta->meta_value;
                                // }
                            ?>
                                <tr>
                                    <td>
                                        <ul class="gallery">
                                            <li>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 64px;">
                                                        <a href="#">
                                                        <?php echo $this->tag->image(array($memberMetaImage)); ?>
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="extras">
                                                    <div class="extras-inner">
                                                        <?php echo $this->tag->linkTo(array($memberMetaImage, '<i class="fa fa-search"></i> ', 'class' => 'colorbox-image', 'rel' => 'group-1')) ?>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </td>
                                    <td><?php echo $memberCode ?></td>
                                    <td><?php echo $firstname = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $member->firstname) : $memberTitle . ' ' . $member->firstname . ' ' . $member->lastname ?></td>
                                    <td><?php echo $memberType ?></td>
                                    <td><?php echo $mt->_("School") . $academyName ?></td>
                                    <td class='hidden-350'>
                                        <?php echo '<span class="label label-default">' . $areaNumber . '</span>'; ?>
                                        <?php echo '<span class="label label-default">' . $province . '</span>'; ?>
                                    </td>

                                    <td class='hidden-350'><?php echo $activeStatus = ($member->status) ? '<span class="label label-satgreen">' . $t->_("Active") . '</span>' : '<span class="label label-lightred">' . $t->_("Inactive") . '</span>'; ?></td>

                                    <td><?php echo $registered ?></td>
                                    <td class='hidden-480'>
                                        <?php echo $this->tag->linkTo(array("members/view/" . $member->member_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                        <?php echo $this->tag->linkTo(array("members/edit/" . $member->member_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                        <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $member->member_id ?>', '<?php echo $memberTitle . ' ' . $member->firstname . ' ' . $member->lastname ?>')"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                        <div class="tables-info pull-left">
                            <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                        </div>

                        <div class="table-pagination pull-right">
                            <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                            <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                            <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                            <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#members.panel-collapse collapse in -->
            </div>
        </div>
        <!-- /.panel-group -->
    </div>
</div>