<?php use Phoenix\Models\Province; ?>

<?php $this->partial("common/partials/page-header", array('title' => $t->_("Mapping Membership Card"), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>
<!-- <div class="row">
    <div class="col-sm-12">
        <div class="pull-left">
            <?php echo $this->tag->linkTo(array("members", '<i class="fa fa-reply"></i> ' . $mt->_("Back"), 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Back"))) ?>
        </div>
        <div class="pull-right">

        </div>
    </div>
</div> -->

<?php echo $this->tag->hiddenField("lot_id") ?>

    <div class="row">
        <div class="col-sm-6">
            <div class="box box-bordered box-color">
                <div class="box-title">
                    <h3>
                        <i class="fa fa-bars"></i>
                        <?php echo $t->_("Citizen Id"); ?>
                    </h3>
                </div>
                <div class="box-content">
                    <div class="row">
                        <?php echo $this->tag->form(array("members/mapping", "method" => "post", "class" => "form-validate form-vertical form-column", 'id' => "frmFindMember")) ?>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <?php echo $this->tag->textField(array("citizenid", "size" => 30, 'class' => 'form-control', 'tabindex' => 14)) ?>
                                         <a href="#" class="btn btn-primary input-group-addon" id="findMember">
                                            <i class="fa fa-search"></i>
                                            <?php echo $t->_("Find Member"); ?>
                                        </a>
                                    </div>
                                    <span class="help-block">
                                        <?php echo $t->_("Please enter citizen id"); ?>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="box box-bordered box-color">
                <div class="box-title">
                    <h3>
                        <i class="fa fa-bars"></i>
                        <?php echo $t->_("Card Id"); ?>
                    </h3>
                </div>
                <div class="box-content">
                    <div class="row">
                        <div class="col-sm-12">
                            <?php echo $this->tag->form(array("members/mapping", "method" => "post", "class" => "form-validate form-vertical form-column", 'id' => "frmMappingMember")) ?>

                                <div class="form-group">
                                    <div class="input-group">
                                        <?php echo $this->tag->textField(array("card_id", "size" => 30, 'class' => 'form-control', 'tabindex' => 15)) ?>
                                        <a href="#" class="btn btn-primary input-group-addon" id="findMember">
                                            <i class="fa fa-link"></i>
                                            <?php echo $t->_("Mapping Member Card"); ?>
                                        </a>
                                    </div>
                                        <span class="help-block">
                                            <?php echo $t->_("Please enter a card id"); ?>
                                        </span>

                                    <?php echo $this->tag->hiddenField("mapping_member_id") ?>
                                    <?php echo $this->tag->hiddenField("mapping_card_id") ?>
                                    <?php echo $this->tag->hiddenField("mapping_citizenid") ?>
                                    <?php echo $this->tag->hiddenField("mapping_lot_id") ?>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php $this->partial("members/partials/memberProfile") ?>


<script>
    $(document).ready(function() {

        $('#citizenid').focus();

        // var $targets = $('#frmFindMember').find('input, button'),
        //     steps = $targets.map(function() {
        //         return $(this).attr('tabindex');
        //     }).get();

        // $('#frmFindMember').on('keypress', 'input, button', function(e) {
        //     if (e.keyCode == 13) {
        //         var current = $.inArray($(this).attr('tabindex'), steps),
        //             next = steps[++current % steps.length];
        //         $targets.filter('[tabindex="' + next + '"]').focus();

        //         // return false;
        //     }
        // });

        $('#findMember').click(function() {
            $('#frmFindMember').submit();
        });

        $('#frmFindMember').submit(function() {


            $('#profile').fadeOut('slow');
            // $('.spinner-load').fadeIn("slow");

            citizenid = $("input[name=citizenid]").val();

            var data = {
              "citizenid": citizenid
            };
            data = $(this).serialize() + "&" + $.param(data);

            $.ajax({
                url: '/members/grabMember/citizenid',
                
                type: 'POST',
                dataType: "json",
                data: data,
                success: function (data) {
                    if(data.status == 'success'){
                        // $('.spinner-load').hide();
                        $('#profile').fadeIn('slow');

                        $('#mapping_member_id').val(data.memberId);
                        $('#type').html(data.memberType);
                        $('#name').html(data.memberName);
                        $('#name_en').html(data.memberNameEN);
                        $('#citizen_id').html(data.memberCitizenId);
                        $('#code').html(data.memberCode);
                        $('#bloodgroup').html(data.memberBloodGroup);
                        $('#image').html(data.memberImage);
                        $('#academy_province').html(data.memberAcademyProvince);
                        $('#academy').html(data.memberAcademy);
                        $('#geo').html(data.memberGeo);

                        // $("input[name=citizenid]").val('');
                        $("input[name=card_id]").focus();
                    }
                    else{
                        alert(data.msg);
                    }

                    console.log(data);
                    // alert(data.memberName)
                }, 
                error: function (xhr, status, data) {  
                  console.log(status);
                  alert('<?php echo $t->_("Data Not Found"); ?> (' + status + ')'); 
                }  
            });

            return false; // keeps the page from not refreshing 
        });


        $('#frmMappingMember').submit(function() {
            $('#mapping_card_id').val($('#card_id').val());
            $('#mapping_citizenid').val($('#citizenid').val());
            $('#mapping_lot_id').val($('#lot_id').val());
        });

    });

</script>