<?php use Phoenix\Models\Academy; ?>
<?php use Phoenix\Models\MembersMeta; ?>
<?php $this->partial("common/partials/page-header", array('title' => $t->_('Membership Qualify Data') . ' ' . $memberTotal . ' ' . $t->_('Person(s)') . ' (' . $filterTitle . ' <span class="filterMember loader loader-blue"></span> ' . $t->_('Person(s)') . ') ', 'size' => 'big')) ?>

<?php echo $this->getContent() ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("members/export/qualify/passed", '<i class="fa fa-file-excel-o"></i> ' . $t->_("Export Passed Members") . ' (<span class="passMember loader loader-gray"></span>)', 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Export Pass Members"))) ?>

            <?php echo $this->tag->linkTo(array("members/export/qualify/notpass", '<i class="fa fa-file-excel-o"></i> ' . $t->_("Export Not Pass Members") . ' (<span class="notPassMember loader loader-gray"></span>)', 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Export Not Pass Members"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel-group panel-widget" id="ac3">
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#members" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-table"></i> <?php echo $t->_('Membership Qualify Data') . ' ' . $memberTotal . ' ' . $t->_('Person(s)') . ' (' . $filterTitle . ' <span class="filterMember "></span> ' . $t->_('Person(s)') . ') '; ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="members" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-hover table-nomargin table-bordered bigrow">
                            <thead>
                                <tr>
                                    <th><?php echo $t->_("Image"); ?></th>
                                    <th><?php echo $t->_("Name"); ?></th>
                                    <th><?php echo $t->_("Name EN"); ?></th>
                                    <th><?php echo $t->_("Citizen Id"); ?></th>
                                    <th class='hidden-480 col-sm-1'><?php echo $t->_("Code"); ?></th>
                                    <th><?php echo $t->_("Member Type"); ?></th>
                                    <th><?php echo $t->_("Blood Group"); ?></th>
                                    
                                    <th><?php echo $mt->_("Status") . $mt->_("Image"); ?></th>
                                    <th><?php echo $t->_("Image Size"); ?></th>
                                    <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php 
                                $rowPassedMember = 0;
                                $rowNotPassedMember = 0;
                                foreach ($page->items as $member) { 

                                $elementPeopleType = $this->elements->getMembersType();
                                $memberType = $elementPeopleType[$member->type];
                                $memberType = str_replace(' (ผู้อำนวยการ)', '', $memberType);
                                $memberType = str_replace(' (รองผู้อำนวยการ)', '', $memberType);


                                $elementPrefix = $this->elements->getPrefixNameData();
                                $memberTitle = $elementPrefix[$member->title];

                                $elementPrefix =$this->elements->getPrefixNameEnData();
                                $memberTitleEn = $elementPrefix[$member->title];

                                $registered = $this->datetime->date(strtotime($member->registered));

                                $academyName = $defaultNullData;
                                $areaName = $defaultNullData;
                                if(!empty($member->membersAcademy->academy_id)){
                                        $academy = Academy::findFirstByAcademy_id($member->membersAcademy->academy_id);
                                    if($academy){
                                        $academyName = $academy->name;
                                        $areaName = $academy->area->name;
                                    }
                                }

                                $areaNameSearch = strpos($areaName, "เขต");
                                if ($areaNameSearch == true) {
                                    $areaNumber = str_replace("สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาเขต", "", $areaName);
                                }else{
                                    $areaNumber = str_replace("องค์กรปกครองส่วนท้องถิ่น ", "", $areaName);
                                }

                                // $province = $member->province->province_name;
                                $province = $academy->province->province_name;

                                $memberCode = (empty($member->code)) ? $defaultNullData : $member->code;

                                $memberCode = str_replace(' ', '', $memberCode);
                                $memberCode = str_replace('ว.', 'ว', $memberCode);
                                $memberCode = str_replace('ว', 'ว ', $memberCode);

                                if($member->type == 2)
                                    if(!strstr($memberCode, 'ว '))
                                        $memberCode = 'ว ' . $memberCode;

                                $membersMeta = MembersMeta::find("member_id = " . $member->member_id );

                               
                                $memberMetaImage = $defaultMemberImage;
                                $memberImageSize[0] = $memberImageSize[1] = 0;
                                unset($memberMetaArray);
                                foreach ($membersMeta as $memberMeta) {
                                    if($memberMeta->meta_key == 'image'){
                                        $memberMetaImage = $uploadLocation . $memberMeta->meta_value;
                                        if(file_exists($memberMetaImage))
                                            $memberImageSize = getimagesize($memberMetaImage);
                                    }
                                    else{
                                        $memberMetaArray[$memberMeta->meta_key] = $memberMeta->meta_value;
                                    }
                                }

                                if( !isset($memberMetaArray['firstname_en']) )
                                    $memberMetaArray['firstname_en'] = '';

                                if( !isset($memberMetaArray['lastname_en']) )
                                    $memberMetaArray['lastname_en'] = '';


                                if( /*$memberImageSize[0] < 300  &&*/ $memberImageSize[0] >= 150 && $memberImageSize[1] != 0 && $memberCode != 'N/A'){
                                    $validateStatus = '<span class="label label-satgreen">' . $t->_("Pass") . '</span>';
                                    $validate = 'pass';
                                }
                                else{
                                    $validateStatus = '<span class="label label-lightred">' . $t->_("Not Pass") . '</span>';
                                    $validate = 'notpass';
                                }

                                if($filter == 'passed')
                                    if($validate ==  'notpass'){
                                        $rowNotPassedMember++;
                                        continue;
                                    }
                                    else{
                                        $rowPassedMember++;
                                    }

                                if($filter == 'notpass')
                                    if($validate ==  'pass'){
                                        $rowPassedMember++;
                                        continue;
                                    }else{
                                        $rowNotPassedMember++;
                                    }

                            ?>
                                <tr>
                                    <td>
                                        <ul class="gallery">
                                            <li>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 64px;">
                                                        <a href="#">
                                                        <?php echo $this->tag->image(array($memberMetaImage)); ?>
                                                        </a><br>
                                                    </div>
                                                </div>
                                                <div class="extras">
                                                    <div class="extras-inner">
                                                        <?php echo $this->tag->linkTo(array($memberMetaImage, '<i class="fa fa-search"></i> ', 'class' => 'colorbox-image', 'rel' => 'group-1')) ?>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                        <?php #echo $memberMetaImage; ?>
                                    </td>

                                    <td><?php echo $firstname = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $member->firstname) : $memberTitle . ' ' . $member->firstname . ' ' . $member->lastname ?>
                                    </td>
                                    <td><?php  echo $memberTitleEn . ' ' . ucwords(strtolower($memberMetaArray['firstname_en'])) . ' ' . ucwords(strtolower($memberMetaArray['lastname_en'])) ?>
                                    </td>
                                    <td class='hidden-350'>
                                        <?php echo $member->citizenid ?>
                                    </td>
                                    <td><?php echo $memberCode ?></td>
                                    <td><?php echo $memberType ?></td>
                                    <td><?php echo $member->bloodgroup ?></td>
                                    

                                    <td class='hidden-350'><?php echo $validateStatus; ?></td>

                                    <td><?php echo $memberImageSize[0] . 'x' . $memberImageSize[1] ?></td>
                                    <td class='hidden-480'>
                                        <?php echo $this->tag->linkTo(array("members/view/" . $member->member_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                        <?php echo $this->tag->linkTo(array("members/edit/" . $member->member_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                        <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $member->member_id ?>', '<?php echo $memberTitle . ' ' . $member->firstname . ' ' . $member->lastname ?>')"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                        <div class="tables-info pull-left">
                            <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                        </div>

                        <div class="table-pagination pull-right">
                            <a href="<?php echo $baseUri ?>members/qualify/<?php echo $filter . '/' .$searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                            <a href="<?php echo $baseUri ?>members/qualify/<?php echo $filter . '/' .$searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                            <a href="<?php echo $baseUri ?>members/qualify/<?php echo $filter . '/' .$searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                            <a href="<?php echo $baseUri ?>members/qualify/<?php echo $filter . '/' .$searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#members.panel-collapse collapse in -->
            </div>
        </div>
        <!-- /.panel-group -->
    </div>
</div>



<script type="text/javascript">

    $(document).ready(function() {
        $('.passMember').text('<?php echo $rowPassedMember ?>').removeClass('loader-blue').removeClass('loader-gray');
        $('.notPassMember').text('<?php echo $rowNotPassedMember ?>').removeClass('loader-blue').removeClass('loader-gray');

        $('.filterMember').text('<?php echo ($filter == 'passed') ? $rowPassedMember : $rowNotPassedMember ?>').removeClass('loader-blue').removeClass('loader-gray');

    });

</script>