<?php use Phoenix\Models\Academy; ?>
<?php use Phalcon\Tag; ?>

<?php $this->partial("common/partials/page-header", array('title' => $t->_("Search Member"), 'size' => 'big')) ?>

<?php echo $this->getContent(); ?>

<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>
<?php echo $this->getContent(); ?>

<?php if(isset($keyword)) :?>
<div class="row">
    <div class="col-sm-12" style="margin-top:20px;">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $mt->_("Search result(s) for", array("keyword" => $keyword)) ?>
        </div>
    </div>
</div>
<?php endif ?>


<div class="row">
    <div class="col-sm-12">
        <div class="pull-left">
            <?php echo $this->tag->linkTo(array("members", '<i class="fa fa-reply"></i> ' . $mt->_("Back"), 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Back"))) ?>
        </div>

        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("members/new", '<i class="fa fa-plus"></i> ' . $t->_("Create Member"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Create Member"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="box box-color box-bordered">
            <div class="box-title">
                <h3>
                    <i class="fa fa-table"></i><?php echo $t->_("Member"); ?>
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-hover table-nomargin table-bordered">
                            <thead>
                                <tr>
                                    <th class='hidden-480 col-sm-1'><?php echo $t->_("Code"); ?></th>
                                    <th><?php echo $t->_("Name"); ?></th>
                                    <th><?php echo $t->_("Member Type"); ?></th>
                                    <th><?php echo $mt->_("School"); ?></th>
                                    <th><?php echo $t->_("Location"); ?></th>
                                    <th><?php echo $mt->_("Status"); ?></th>
                                    <th><?php echo $t->_("Registered"); ?></th>
                                    <th class='hidden-480 col-sm-2'><?php echo $mt->_("Options"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($page->items as $member) { 

                                $elementPeopleType = $this->elements->getMembersType();
                                $memberType = $elementPeopleType[$member->type];


                                $elementPrefix =$this->elements->getPrefixNameData();
                                $memberTitle = $elementPrefix[$member->title];

                                $registered = $this->datetime->date(strtotime($member->registered));

                                $academy = Academy::findFirstByAcademy_id($member->membersAcademy->academy_id);
                                $academyName = $academy->name;
                                $areaName = $academy->area->name;

                                $areaNameSearch = strpos($areaName, "เขต");
                                if ($areaNameSearch == true) {
                                    $areaNumber = str_replace("สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาเขต", "", $areaName);
                                }else{
                                    $areaNumber = str_replace("องค์กรปกครองส่วนท้องถิ่น ", "", $areaName);
                                }

                                $province = $member->province->province_name;
                            ?>
                                <tr>
                                    <td><?php echo $member->code ?></td>
                                    <td><?php echo $firstname = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $memberTitle . ' ' . $member->firstname . ' ' . $member->lastname) : $memberTitle . ' ' . $member->firstname . ' ' . $member->lastname ?></td>
                                    <td><?php echo $memberType ?></td>
                                    <td><?php echo $mt->_("School") . $academyName ?></td>
                                    <td class='hidden-350'>
                                        <?php echo '<span class="label label-default">' . $areaNumber . '</span>'; ?>
                                        <?php echo '<span class="label label-default">' . $province . '</span>'; ?>
                                    </td>

                                    <td class='hidden-350'><?php echo $activeStatus = ($member->status) ? '<span class="label label-satgreen">' . $t->_("Active") . '</span>' : '<span class="label label-lightred">' . $t->_("Inactive") . '</span>'; ?></td>

                                    <td><?php echo $registered ?></td>
                                    <td class='hidden-480'>
                                        <?php echo $this->tag->linkTo(array("members/view/" . $member->member_id, '<i class="fa fa-eye"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("View"))); ?>
                                        <?php echo $this->tag->linkTo(array("members/edit/" . $member->member_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                        <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $member->member_id ?>', '<?php echo $member->title . ' ' . $member->firstname . ' ' . $member->lastname ?>')"><i class="fa fa-trash-o"></i></a>

                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                <div class="tables-info pull-left">
                    <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                </div>

                <div class="table-pagination pull-right">
                    <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                    <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                    <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                    <a href="<?php echo $baseUri ?>members/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->partial("members/partials/modalDeleteConfirm", array('title' => 'Delete Items', 'size' => 'big')) ?>
