<?php $this->partial("/../../../views/common/partials/page-header", array('title' => $t->_("AcademicYear"), 'size' => 'big')) ?>

<?php echo $this->getContent() ?>
<div class="breadcrumbs">
    <ul>
        <?php $this->crumbs->render();?>
    </ul>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="pull-right">
            <?php echo $this->tag->linkTo(array("settings/academicyears/new", '<i class="fa fa-plus"></i> ' . $t->_("Create AcademicYear"), 'class' => 'btn btn-primary', 'rel' => 'tooltip', 'title' => $t->_("Create AcademicYear"))) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel-group panel-widget" id="ac3">
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#academicyears" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-table"></i> <?php echo $t->_("AcademicYear"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>

                <!-- /.panel-heading -->
                <div id="academicyears" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-hover table-nomargin table-bordered">
                            <thead>
                                <tr>
                                    <th><?php echo $t->_("Id"); ?></th>
                                    <th><?php echo $t->_("AcademicYear Name"); ?></th>
                                    <th><?php echo $t->_("AcademicYear Term"); ?></th>
                                    <th><?php echo $t->_("AcademicYear Start"); ?></th>
                                    <th><?php echo $t->_("AcademicYear End"); ?></th>
                                    <th class='hidden-480 col-sm-1'><?php echo $mt->_("Options"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php 
                            foreach ($page->items as $academicyear) { ?>
                                <tr>
                                    <td><?php echo $id = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->academicyear_id) : $academicyear->academicyear_id ?></td>
                                    <td><?php echo $name = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->name) : $academicyear->name ?></td>
                                    <td><?php echo $term = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->term) : $academicyear->term ?></td>
                                    <td><?php echo $start = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->start) : $academicyear->start ?></td>
                                    <td><?php echo $end = isset($keyword) ? str_replace($keyword, '<strong>'.$keyword.'</strong>', $academicyear->end) : $academicyear->end ?></td>
                                    <td class='hidden-480'>
                                        <?php echo $this->tag->linkTo(array("settings/academicyears/edit/" . $academicyear->academicyear_id, '<i class="fa fa-edit"></i>', 'class' => 'btn', 'rel' => 'tooltip', 'title' => $mt->_("Edit"))); ?>
                                        <a href="#modalDeleteConfirm" role="button" class="btn" rel="tooltip" title="<?php echo $mt->_("Delete") ?>" data-original-title="<?php echo $mt->_("Delete")?>" data-toggle="modal" onclick="deleteConfirm('<?php echo $academicyear->academicyear_id ?>', '<?php echo $academicyear->name ?>')"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            <?php }
                         ?>
                            </tbody>
                        </table>

                        <div class="tables-info pull-left">
                            <?php echo $mt->_("Showing page") . " <span>", $page->current, "</span> " . $mt->_("of") . " <span>", $page->total_pages, "</span> " . $mt->_("pages") . " (<span>", $page->total_items, "</span> " . $mt->_("entries") . ")"; ?>
                        </div>

                        <div class="table-pagination pull-right">
                            <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>"><i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"> <?php echo $mt->_("First"); ?></i></a>
                            <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>?page=<?= $page->before; ?>"><i class="fa fa-chevron-left"> <?php echo $mt->_("Previous"); ?></i></a>

                            <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>?page=<?= $page->next; ?>"><?php echo $mt->_("Next"); ?> <i class="fa fa-chevron-right"></i></a>
                            <a href="<?php echo $baseUri ?>settings/academicyears/<?php echo $searchType ?>?page=<?= $page->last; ?>"><?php echo $mt->_("Last"); ?> <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#academicyears.panel-collapse collapse in -->
            </div>

            <!-- /.panel panel-default -->
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#basic" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-search"></i> <?php echo $mt->_("Basic Search"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="basic" class="panel-collapse collapse">
                    <div class="panel-body">
                        <?php echo $this->tag->form(array("settings/academicyears/basicsearch", "method" => "post", "autocomplete" => "off", "class" => "form-vertical form-column form-bordered search-form")) ?>
                            <div class="input-group ">
                                <?php echo $this->tag->textField(array("keyword", 'class' => 'form-control', 'placeholder' => $mt->_("Search here..."))) ?>
                                <div class="input-group-btn">
                                    <?php echo $this->tag->submitButton(array($mt->_('Search!'), 'class' => 'btn btn-primary btn-large input-group-addon')) ?>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#basic.panel-collapse collapse -->
            </div>
            <!-- /.panel panel-default -->
            <div class="panel panel-default darkblue">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#advance" data-toggle="collapse" data-parent="#ac3">
                            <i class="fa fa-search"></i> <?php echo $mt->_("Advanced Search"); ?>
                        </a>
                    </h4>
                    <!-- /.panel-title -->
                </div>
                <!-- /.panel-heading -->
                <div id="advance" class="panel-collapse collapse">
                    <div class="panel-body">
                        <?php echo $this->tag->form(array("settings/academicyears/search", "method" => "post", "class" => "form-vertical form-column form-bordered", 'enctype' => 'multipart/form-data')) ?>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="col-sm-6 col-left">
                                            <div class="form-group">
                                                <label for="name" class="control-label"><?php echo $t->_("AcademicYear Name"); ?></label>
                                                <?php echo $form->render("name") ?>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-right">
                                            <div class="form-group">
                                                <label for="publisher" class="control-label"><?php echo $t->_("AcademicYear Term"); ?></label><br><br>
                                                <?php echo $form->render("term") ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6 col-left">
                                            <div class="form-group">
                                                <label for="publisher" class="control-label"><?php echo $t->_("AcademicYear Start"); ?></label>
                                                <?php echo $form->render("start") ?>
                                            </div>
                                        </div>

                                        <div class="col-sm-6 col-right">
                                            <div class="form-group">
                                                <label for="publisher" class="control-label"><?php echo $t->_("AcademicYear End"); ?></label>
                                                <?php echo $form->render("end") ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-actions pull-right">
                                                <?php echo $this->tag->submitButton(array($mt->_('Search!'), 'class' => 'btn btn-primary btn-large')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /#advance.panel-collapse collapse in -->
            </div>
            <!-- /.panel panel-default -->
        </div>
        <!-- /.panel-group -->
    </div>
</div>

<?php $this->partial("academicyears/partials/modalDeleteConfirm", array('title' => $t->_("Delete AcademicYear"), 'size' => 'big')) ?>